- name: Playbook de test Ansible
  hosts: all
  become: yes
  tasks:
    - name: Vérifier si apt-get est installé
      command: which apt-get
      register: apt_get_check
      ignore_errors: yes

    - name: Installer apt-get si manquant
      apt:
        name: apt
        state: present
      when: apt_get_check.rc != 0

    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: apt_get_check.rc == 0

    - name: Exemple d'installation d'un paquet
      apt:
        name: curl
        state: present
      when: apt_get_check.rc == 0
