- name: Playbook de test Ansible
  hosts: all
  become: yes
  tasks:
    - name: Vérifier si yum est installé
      command: which yum
      register: yum_check
      ignore_errors: yes

    - name: Vérifier si yum est disponible
      fail:
        msg: "Yum n'est pas installé sur le système distant."
      when: yum_check.rc != 0

    - name: Mettre à jour la liste des paquets
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Exemple d'installation d'un paquet
      yum:
        name: curl
        state: present
